swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /aprobacion_documentos/aprobar_documentos:
    post:
      tags:
      - aprobacion_documentos
      description: create AprobarSolicitudes
      operationId: AprobacionDocumentosController.AprobarSolicitudes
      responses:
        "201":
          description: ""
        "403":
          description: ""
  /aprobacion_documentos/certificacion_visto_bueno/{dependencia}/{mes}/{anio}:
    get:
      tags:
      - aprobacion_documentos
      description: create CertificacionVistoBueno
      operationId: AprobacionDocumentosController.CertificacionVistoBueno
      parameters:
      - in: query
        name: dependencia
        description: Dependencia del contrato en la tabla vinculacion
        required: true
        type: integer
        format: int64
      - in: query
        name: mes
        description: Mes del pago mensual
        required: true
        type: integer
        format: int64
      - in: query
        name: anio
        description: Año del pago mensual
        required: true
        type: integer
        format: int64
      responses:
        "201":
          description: ""
        "403":
          description: :anio is empty
  /aprobacion_documentos/solicitudes_coordinador/{doccoordinador}:
    get:
      tags:
      - aprobacion_documentos
      description: create SolicitudesCoordinador
      operationId: AprobacionDocumentosController.SolicitudesCoordinador
      parameters:
      - in: query
        name: doccoordinador
        description: Número del documento del coordinador
        required: true
        type: string
      responses:
        "201":
          description: ""
        "403":
          description: :doccoordinador is empty
  /aprobacion_documentos/solicitudes_supervisor/{docsupervisor}:
    get:
      tags:
      - aprobacion_documentos
      description: create SolicitudesSupervisor
      operationId: AprobacionDocumentosController.SolicitudesSupervisor
      parameters:
      - in: query
        name: docsupervisor
        description: Número del documento del supervisor
        required: true
        type: string
      responses:
        "201":
          description: ""
        "403":
          description: :docsupervisor is empty
  /aprobacion_pago/aprobar_pagos:
    post:
      tags:
      - aprobacion_pago
      description: create AprobarPagos
      operationId: AprobacionPagoController.AprobarPagos
      responses:
        "201":
          description: ""
        "403":
          description: ""
  /aprobacion_pago/certificacion_documentos_aprobados/{dependencia}/{mes}/{anio}:
    get:
      tags:
      - aprobacion_pago
      description: create CertificacionDocumentosAprobados
      operationId: AprobacionPagoController.CertificacionDocumentosAprobados
      parameters:
      - in: query
        name: dependencia
        description: Dependencia del contrato en la tabla ordenador_gasto
        required: true
        type: integer
        format: int64
      - in: query
        name: mes
        description: Mes del pago mensual
        required: true
        type: integer
        format: int64
      - in: query
        name: anio
        description: Año del pago mensual
        required: true
        type: integer
        format: int64
      responses:
        "201":
          description: ""
        "403":
          description: :anio is empty
  /aprobacion_pago/dependencia_ordenador/{docordenador}:
    get:
      tags:
      - aprobacion_pago
      description: create DependenciaOrdenador
      operationId: AprobacionPagoController.DependenciaOrdenador
      parameters:
      - in: query
        name: docordenador
        description: Número del documento del ordenador
        required: true
        type: string
      responses:
        "201":
          description: ""
        "403":
          description: :docordenador is empty
  /aprobacion_pago/informacion_ordenador/{numero_contrato}/{vigencia}:
    get:
      tags:
      - aprobacion_pago
      description: create ObtenerInfoOrdenador
      operationId: AprobacionPagoController.ObtenerInfoOrdenador
      parameters:
      - in: query
        name: numero_contrato
        description: Numero de contrato en la tabla contrato general
        required: true
        type: integer
        format: int64
      - in: query
        name: vigencia
        description: Vigencia del contrato en la tabla contrato general
        required: true
        type: integer
        format: int64
      responses:
        "201":
          description: '{int} models.InformacionOrdenador'
        "403":
          description: :vigencia is empty
  /aprobacion_pago/pago_aprobado/{numero_contrato}/{vigencia}/{mes}/{anio}:
    get:
      tags:
      - aprobacion_pago
      description: create PagoAprobado
      operationId: AprobacionPagoController.PagoAprobado
      parameters:
      - in: query
        name: numero_contrato
        description: Numero de contrato en la tabla contrato general
        required: true
        type: integer
        format: int64
      - in: query
        name: vigencia
        description: Vigencia del contrato en la tabla contrato general
        required: true
        type: integer
        format: int64
      - in: query
        name: mes
        description: Mes del pago mensual
        required: true
        type: integer
        format: int64
      - in: query
        name: anio
        description: Año del pago mensual
        required: true
        type: integer
        format: int64
      responses:
        "201":
          description: ""
        "403":
          description: :anio is empty
  /aprobacion_pago/solicitudes_ordenador/{docordenador}:
    get:
      tags:
      - aprobacion_pago
      description: create SolicitudesOrdenador
      operationId: AprobacionPagoController.SolicitudesOrdenador
      parameters:
      - in: query
        name: docordenador
        description: Número del documento del ordenador
        required: true
        type: string
      responses:
        "201":
          description: ""
        "403":
          description: :docordenador is empty
  /informacion_academica/contratos_docente/{numDocumento}:
    get:
      tags:
      - informacion_academica
      description: create GetContratosDocente
      operationId: InformacionAcademicaController.GetContratosDocente
      parameters:
      - in: query
        name: numDocumento
        description: Docente a consultar
        required: true
        type: string
      responses:
        "201":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.ContratosDocentes'
        "403":
          description: body is empty
  /informacion_academica/informacion_coordinador/{id_dependencia_oikos}:
    get:
      tags:
      - informacion_academica
      description: create ObtenerInfoCoordinador
      operationId: InformacionAcademicaController.ObtenerInfoCoordinador
      parameters:
      - in: query
        name: id_dependencia_oikos
        description: Proyecto a obtener información coordinador
        required: true
        type: integer
        format: int64
      responses:
        "201":
          description: '{int} models.InformacionCoordinador'
        "400":
          description: Bad Request
        "403":
          description: :id_dependencia_oikos is empty
definitions:
  models.ContratosDocentes:
    title: ContratosDocentes
    type: object
tags:
- name: informacion_academica
  description: |
    InformacionAcademicaController operations for InformacionAcademica
- name: aprobacion_pago
  description: |
    AprobacionPagoController operations for AprobacionPago
- name: aprobacion_documentos
  description: |
    AprobacionDocumentosController operations for AprobacionDocumentos
