swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /informacion_academica/contratos_docente/{numDocumento}:
    get:
      tags:
      - informacion_academica
      description: create GetContratosDocente
      operationId: InformacionAcademicaController.GetContratosDocente
      parameters:
      - in: query
        name: numDocumento
        description: Docente a consultar
        required: true
        type: string
      responses:
        "201":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.ContratosDocentes'
        "403":
          description: body is empty
  /informacion_academica/informacion_coordinador/{id_dependencia_oikos}:
    get:
      tags:
      - informacion_academica
      description: create ObtenerInfoCoordinador
      operationId: InformacionAcademicaController.ObtenerInfoCoordinador
      parameters:
      - in: query
        name: id_dependencia_oikos
        description: Proyecto a obtener información coordinador
        required: true
        type: integer
        format: int64
      responses:
        "201":
          description: '{int} models.InformacionCoordinador'
        "400":
          description: Bad Request
        "403":
          description: :id_dependencia_oikos is empty
definitions:
  models.ContratosDocentes:
    title: ContratosDocentes
    type: object
tags:
- name: informacion_academica
  description: |
    InformacionAcademicaController operations for InformacionAcademica
